<template>
<div class="base base-scale-in ">
  <slot/>
</div>
</template>

<script setup>

</script>

<style scoped>
.base{
  display: flex;
  flex-direction:row;
  width:100vw;
  background-color: white;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-2-2 23:5:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-fwd-center
 * ----------------------------------------
 */
@-webkit-keyframes slide-fwd-center {
  0% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
  }
  100% {
    -webkit-transform: translateZ(160px);
    transform: translateZ(160px);
  }
}
@keyframes slide-fwd-center {
  0% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
  }
  100% {
    -webkit-transform: translateZ(160px);
    transform: translateZ(160px);
  }
}
.base-scale-in {
  -webkit-animation: slide-fwd-center 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
  animation: slide-fwd-center 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}
</style>